#For demo only not recomended in real world
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accessing-files.fullname" . }}
data:
{{ (.Files.Glob "files/*.properties").AsSecrets |indent 4 }}
